### ISSUE TITLE
cnako3 の -o オプションが使えない

### ISSUE THREAD

**Issue by puni073** [kujirahand/nadesiko3#1864]
`cnako3 -c -o outfile Hello.nako3`
```
[cnako3のエラー] Error: ENOENT: no such file or directory, open 'outfile.nako3'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at CNako3.execCommand (file:///usr/local/lib/node_modules/nadesiko3/src/cnako3mod.mjs:159:24)
    at file:///usr/local/lib/node_modules/nadesiko3/src/cnako3.mjs:10:22
    at file:///usr/local/lib/node_modules/nadesiko3/src/cnako3.mjs:17:3
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'outfile.nako3'
}
```

**Comment by kujirahand** [comment]
@puni073 ご報告ありがとうございます。まずはこちらのIssueを修正しました。

**Comment by kujirahand** [comment]
v3.6.43で修正しました
