### ISSUE TITLE
Some tests fail, with PST as local timezone (UTC -8 hours)

### ISSUE THREAD

**Issue by nobodxbodon** [kujirahand/nadesiko3#233]
```
  3 failing

  1) 関数呼び出しテスト
       連続文後の代入:

      AssertionError [ERR_ASSERTION]: '2017/08/31' == '2017/09/01'
      + expected - actual

      -2017/08/31
      +2017/09/01
      
      at cmp (test/func_call.js:12:12)
      at Context.it (test/func_call.js:46:5)

  2) 関数呼び出しテスト
       連続文後の=代入:

      AssertionError [ERR_ASSERTION]: '2017/08/31' == '2017/09/01'
      + expected - actual

      -2017/08/31
      +2017/09/01
      
      at cmp (test/func_call.js:12:12)
      at Context.it (test/func_call.js:49:5)

  3) PluginSystem test
       日時:

      AssertionError [ERR_ASSERTION]: '1488787200' == '1488726000'
      + expected - actual

      -1488787200
      +1488726000
      
      at cmp (test/func_system_test.js:11:12)
      at Context.it (test/func_system_test.js:149:5)

```

**Comment by massongit** [comment]
『日時変換』関数等の日時に関係した関数のタイムゾーンを以下のような仕様にする。
* デフォルト設定はユーザー側のタイムゾーン
* タイムゾーンを設定する関数を用意する (もしくはオプション引数でタイムゾーンを指定できるようにする)

このようにした上で、テストではタイムゾーンをJSTに設定することで、JST以外のタイムゾーンで動作しているコンピュータ上でもテストが失敗しなくなると考えられる。

**Comment by massongit** [comment]
FYI: [Moment Timezone](https://momentjs.com/timezone/)

**Comment by massongit** [comment]
@nobodxbodon If you have time, would you please pull https://github.com/massongit/nadesiko3/tree/feature/timezone (as #236) and do build and test?

**Comment by nobodxbodon** [comment]
@massongit all tests pass for me (feature/timezone branch). Thanks for the quick fix.

**Comment by massongit** [comment]
@nobodxbodon Thank you for your testing!

**Comment by kujirahand** [comment]
素晴らしい修正！
感謝！！
