### ISSUE TITLE
ビルドできない

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#348]
9aeec57140745f00c4dcfd14c84348dc21959460 以降、ビルドしようとすると、以下のようなエラーが出てしまいます。

```bash
$ npm run build

> nadesiko3@3.0.53 build /home/hoge/Documents/nadesiko3
> webpack --mode production

/home/hoge/Documents/nadesiko3/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/hoge/Documents/nadesiko3/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/hoge/Documents/nadesiko3/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/hoge/Documents/nadesiko3/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nadesiko3@3.0.53 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nadesiko3@3.0.53 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoge/.npm/_logs/2019-01-05T03_54_18_652Z-debug.log

```

**Comment by kujirahand** [comment]
おお、webpackをアップデートしてしまったので、それが影響しているのかも。。。調査してみます。

**Comment by kujirahand** [comment]
4458bb62501f156265184ab3518fbf58234debc2 で修正。
