### ISSUE TITLE
テストが通らない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#503]
@massongit 可変引数の実装、素晴らしいです！！

ところで、最新のリポジトリ( 576b1ed89ff61df1f65c829c56c93949be9a83fc ) で、
``npm test`` 実行するとエラーで動かなくなってます。見て貰ってもよいでしょうか。

**Comment by kujirahand** [comment]
```
$ mocha test/basic_test.js

 1) basic
       連文後の代入文:

      AssertionError [ERR_ASSERTION]: 'undefined' == 'bbcc'
      + expected - actual

      -undefined
      +bbcc

      at cmp (test/basic_test.js:11:12)
      at Context.<anonymous> (test/basic_test.js:66:5)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by kujirahand** [comment]
さっそくの対応ありがとうございました！
素晴らしいです！
