### ISSUE TITLE
タートルグラフィックスが動作しない

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#53]
タートルグラフィックスを実行しようとすると、(例えばsrc/lang/demo/turtle2.htmlの『三角描画』の場合) 以下のようなエラーが発生します。

```
[TURTLE] clearAll
Error: [実行エラー] TypeError:sys.__getSysValue is not a function
__varslist[0].line=0;// なでしこの関数定義
__varslist[0].line=0;// プラグインの初期化
__varslist[0].line=0;__varslist[0]["!PluginTurtle:初期化"](__self)
__varslist[0].line=1;__varslist[0]["カメ全消去"](__self);
__varslist[0].line=2;__vars["それ"] = __varslist[0]["カメ作成"](__self);
__varslist[0].line=2;
__varslist[0].line=3;__vars["それ"] = __varslist[0]["カメ速度設定"](80,__self);
__varslist[0].line=3;
__varslist[0].line=4;__varslist[0]["カメペン色設定"](__varslist[0]["赤色"],__self);
__varslist[0].line=4;
__varslist[0].line=5;for(__vars["N"]/*?:5*/=1; __vars["N"]/*?:5*/<=60; __vars["N"]/*?:5*/++){
  __vars["それ"] = __vars["N"]/*?:5*/;
  __varslist[0].line=6;__varslist[0]["カメ移動"]([(__vars["N"]/*?:6*/*4),(__vars["N"]/*?:6*/*6)],__self);
__varslist[0].line=6;
__varslist[0].line=7;__varslist[0]["カメ移動"]([(280-(__vars["N"]/*?:7*/*4)),(__vars["N"]/*?:7*/*6)],__self);
__varslist[0].line=7;

};
__varslist[0].line=8;


    at new NakoRuntimeError (eval at <anonymous> (http://localhost:63342/nadesiko3/src/lang/release/wnako3.js:74:1), <anonymous>:30:121)
    at WebNakoCompiler._run (eval at <anonymous> (http://localhost:63342/nadesiko3/src/lang/release/wnako3.js:74:1), <anonymous>:167:23)
    at WebNakoCompiler.run (eval at <anonymous> (http://localhost:63342/nadesiko3/src/lang/release/wnako3.js:74:1), <anonymous>:174:25)
    at run_box (http://localhost:63342/nadesiko3/src/lang/demo/turtle_test.js:19:25)
    at HTMLButtonElement.onclick (http://localhost:63342/nadesiko3/src/lang/demo/turtle2.html:32:46)
```

なお、[2349fee](https://github.com/kujirahand/nadesiko3/commit/2349fee)のあたりからこのエラーが発生するようです。

**Comment by massongit** [comment]
NakoCompilerのコンストラクタにおいて、PluginSystemを追加した後にリセットを行っていたため、リセットのタイミングをPluginSystem追加前に変更しました。

**Comment by kujirahand** [comment]
修正ありがとうございます
