### ISSUE TITLE
webpack5 でブラウザのテストが通らない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#873]
c4dacd4f8123a9f8191204d57e1b9d13fbabcde9
でwebpack5に対応したものの、ブラウザのテストで落ちます。

```
START:
Webpack bundling...
18 03 2021 16:57:18.051:ERROR [karma-server]: Error during file loading or preprocessing
Error: Universal Chunk Loading is not implemented yet
    at EnableChunkLoadingPlugin.apply (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/javascript/EnableChunkLoadingPlugin.js:104:12)
    at WebpackOptionsApply.process (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/WebpackOptionsApply.js:156:40)
    at createCompiler (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/webpack.js:78:28)
    at create (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/webpack.js:118:16)
    at webpack (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/webpack.js:142:32)
    at f (/Users/kujiramac/repos/nadesiko3/node_modules/webpack/lib/index.js:41:15)
    at /Users/kujiramac/repos/nadesiko3/node_modules/karma-webpack/lib/karma-webpack/controller.js:85:25
    at new Promise (<anonymous>)
    at KW_Controller._bundle (/Users/kujiramac/repos/nadesiko3/node_modules/karma-webpack/lib/karma-webpack/controller.js:76:12)
    at KW_Controller.bundle (/Users/kujiramac/repos/nadesiko3/node_modules/karma-webpack/lib/karma-webpack/controller.js:68:34)
```

**Comment by kujirahand** [comment]
test_xxx/karma.config.js の修正が必要ですね。

**Comment by yy0931** [comment]
私も以前にwebpack5への移行を試したのですが、ちょうどそのエラーが解決できず諦めました。おそらく、
- webpack 5 はまだnode.jsとwebのどちらでも走るプログラムを出力できず、package.jsonのbrowserlistからnode.jsを削って、Node.jsから動かすときはbundleされた.jsファイルではなくcnako3.jsを直接呼ぶように変える必要がありそうです。
- web用のbundleで__dirnameやrequire('assert')が無いと言われるため、何らかの置換が必要そうです。

**Comment by weyk** [comment]
karmaが以前と同じであれば、preprocessorでリレーしてゆく間、１つの元ファイルにつき、１ストリームしか扱えません。そのため、chunkされてしまうと、２つ目以降のファイルを取りこぼしてしまうことになります（そもそも、ストリームにファイル名も付いてません）
なので、とりあえず、ファイルが分割される可能性のあるpluginは全てエラーにするようにしたのではないでしょうか。

**Comment by kujirahand** [comment]
むむむ、考察ありがとうございます。
ブラウザ向けテスト以外はwebpack5でも動いたのですが、karma.config.jsがうまく直せなかったので、webpack4に戻しました。時間のあるときに、webpack5対策することにします。

**Comment by weyk** [comment]
以下で行けそうです。
・とりあえずbrowserslistからnode削除。
・karma.configのframeworkにwebpack 追加。
・chaiをインストール。
・test_browserとtest_bundledで使用しているassertをchaiのassertに変更。
webworkerだけ失敗します。

assertパッケージ、for  browserのはず何ですがwebpack v4ではnodeポリフィルに頼っていたようです。

**Comment by weyk** [comment]
パッケージのassertを外して試した所、nodeでの動作はnode-coreのassertがあるので大丈夫ですが、じつはブラウザ側で参照していた部分がエラーになります。
確認できた範囲では、nakoが全環境で取り込んでしまっているplugin_testが、assertを使っています。
assertパッケージを用いてwebpack v5でbuildした場合、グローバルにprocessが無くてエラーになります。
（エラーの発見を難しくしているだけのようなので、assertパッケージは外した方がいいかも）

plugin_testについては、現状の機能であれば、パッケージ依存無しでnode/web両方で動くものをミニマムな機能を実装するのがよさそうです。

**Comment by kujirahand** [comment]
そうですね、plugin_testはnode/web両方で動くようにassertは外したいと思います。

**Comment by kujirahand** [comment]
とりあえず、webpack5 には対応できたので、上記の点を #892 で作業しようと思います。
